import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createWorker} from '../worker.mjs';
import {database} from '../scripts/sqlite-adapter.mjs';
import {hash} from 'bcryptjs';
const schema=await fs.readFile('db/schema.sql','utf8');
const assets={'/admin.html':{type:'text/html',body:'admin'},'/index.html':{type:'text/html',body:'shop'}};
test('protected durable product management, stock, conflicts, archive, themes',async()=>{
 const DB=database(),env={DB,ADMIN_USERNAME:'shopadmin',ADMIN_PASSWORD_HASH:await hash('test-password-123',12)},w=createWorker(assets,schema);
 for(const file of (await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())await DB.exec(await fs.readFile('drizzle/'+file,'utf8'));
 let cookie='';
 const call=(path,method='GET',data,auth=true,origin='https://store.test')=>w.fetch(new Request('https://store.test'+path,{method,headers:{'Content-Type':'application/json',Origin:origin,...(auth?{Cookie:cookie}:{})},...(data!==undefined?{body:JSON.stringify(data)}:{})}),env);
 const login=await call('/api/auth/login','POST',{username:env.ADMIN_USERNAME,password:'test-password-123'});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];
 assert.equal((await call('/admin','GET',undefined,false)).status,302);
 assert.equal((await call('/api/admin/products','GET',undefined,false)).status,403);
 assert.equal((await call('/admin')).status,200);
 assert.equal((await w.fetch(new Request('https://store.test/admin',{headers:{'oai-authenticated-user-email':'owner@example.com'}}),env)).status,302);
 assert.equal((await call('/admin.html')).status,404);
 const p={name:'iPhone teste <script>',category:'iPhone',description:'128 GB',price:199900,stock:3,low_stock:2,image:'',condition:'Novo',featured:true,published:true};
 assert.equal((await call('/api/admin/products','POST',p,true,'https://evil.test')).status,403);
 assert.equal((await call('/api/admin/products','POST',{...p,stock:-1})).status,400);
 assert.equal((await call('/api/admin/products','POST',{...p,image:'javascript:alert(1)'})).status,400);
 const created=await call('/api/admin/products','POST',p);assert.equal(created.status,201);const {product}=await created.json();
 let catalog=await (await call('/api/catalog','GET',undefined,false)).json();assert.equal(catalog.products.length,1);assert.equal(catalog.products[0].price,p.price);
 const url='/api/admin/products/'+product.id;
 assert.equal((await call(url,'PUT',{...p,stock:0,version:1})).status,200);
 assert.equal((await call(url,'PUT',{...p,stock:4,version:1})).status,409);
 catalog=await (await call('/api/catalog','GET',undefined,false)).json();assert.equal(catalog.products[0].stock,0);
 assert.equal((await call(url,'PUT',{...p,published:false,version:2})).status,200);
 assert.equal((await (await call('/api/catalog','GET',undefined,false)).json()).products.length,0);
 assert.equal((await call(url,'PATCH',{archived:true,version:3})).status,200);
 assert.equal((await call(url,'PATCH',{archived:false,version:4})).status,200);
 const s=await (await call('/api/admin/settings')).json();
 assert.equal((await call('/api/admin/settings','PUT',{theme:'dark',accent:'blue',version:s.version})).status,200);
 assert.equal((await call('/api/admin/settings','PUT',{theme:'light',accent:'orange',version:s.version})).status,409);
 const restarted=createWorker(assets,schema);const after=await (await restarted.fetch(new Request('https://store.test/api/catalog'),env)).json();assert.equal(after.settings.theme,'dark');
 const invalid=await w.fetch(new Request('https://store.test/api/admin/products',{headers:{'oai-authenticated-user-id':'other','oai-authenticated-user-email':'other@example.com'}}),env);assert.equal(invalid.status,403);DB.close();
});
