import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {hash,compare} from 'bcryptjs';
import {createWorker} from '../worker.mjs';
import {database} from '../scripts/sqlite-adapter.mjs';

test('accounts, server authorization, session expiry/revocation, CSRF and throttling',async()=>{
 const DB=database(),env={DB,ADMIN_USERNAME:'shopadmin',ADMIN_PASSWORD_HASH:await hash('admin-test-password',12)};
 const schema=await fs.readFile('db/schema.sql','utf8');
 for(const file of (await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())await DB.exec(await fs.readFile('drizzle/'+file,'utf8'));
 const assets={'/admin.html':{type:'text/html',body:'admin'},'/account.html':{type:'text/html',body:'account'}};
 const w=createWorker(assets,schema);
 const call=(path,data,cookie='',origin='https://shop.test',method=data===undefined?'GET':'POST')=>w.fetch(new Request('https://shop.test'+path,{method,headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie,'oai-authenticated-user-email':'owner@example.com','cf-connecting-ip':'192.0.2.1'},...(data===undefined?{}:{body:JSON.stringify(data)})}),env);
 const customer={username:'cliente_teste',password:'customer-password',name:'Cliente Teste',role:'admin'};
 assert.equal((await call('/api/admin/products')).status,403);
 assert.equal((await call('/admin')).status,302);
 assert.equal((await call('/admin.html')).status,404);
 assert.equal((await call('/conta')).status,200);
 assert.equal((await call('/api/auth/register',customer,'','https://evil.test')).status,403);
 assert.equal((await call('/api/auth/register',{...customer,username:'SHOPADMIN'})).status,409);
 assert.equal((await call('/api/auth/login',null)).status,400);
 const registered=await call('/api/auth/register',customer);assert.equal(registered.status,200);
 assert.equal((await registered.json()).user.role,'customer');
 const header=registered.headers.get('set-cookie');assert.match(header,/HttpOnly/);assert.match(header,/Secure/);assert.match(header,/SameSite=Lax/);assert.match(header,/__Host-/);
 const customerCookie=header.split(';')[0];
 const record=await DB.prepare('SELECT * FROM accounts WHERE username=?').bind(customer.username).first();assert.notEqual(record.password_hash,customer.password);assert.equal(await compare(customer.password,record.password_hash),true);
 assert.equal((await call('/api/auth/register',customer)).status,409);
 assert.equal((await call('/api/admin/products',undefined,customerCookie)).status,403);
 assert.equal((await call('/api/admin/settings',{theme:'dark'},customerCookie,'https://shop.test','PUT')).status,403);
 assert.equal((await call('/admin',undefined,customerCookie)).status,302);
 assert.equal((await call('/api/auth/session',undefined,customerCookie)).status,200);
 const restarted=createWorker(assets,schema);const restored=await restarted.fetch(new Request('https://shop.test/api/auth/session',{headers:{Cookie:customerCookie}}),env);assert.equal((await restored.json()).user.username,customer.username);
 assert.equal((await call('/api/auth/login',{username:env.ADMIN_USERNAME,password:'incorrect-password'})).status,401);
 const admin=await call('/api/auth/login',{username:env.ADMIN_USERNAME,password:'admin-test-password'});assert.equal(admin.status,200);
 const adminCookie=admin.headers.get('set-cookie').split(';')[0];assert.equal((await admin.json()).user.role,'admin');
 assert.equal((await call('/admin',undefined,adminCookie)).status,200);
 assert.equal((await call('/api/admin/products',undefined,adminCookie)).status,200);
 assert.equal((await call('/api/admin/settings',{theme:'dark'},adminCookie,'https://evil.test','PUT')).status,403);
 assert.equal((await call('/api/auth/logout',{},adminCookie,'https://evil.test')).status,403);
 assert.equal((await call('/api/auth/logout',{},adminCookie)).status,200);
 assert.equal((await call('/api/admin/products',undefined,adminCookie)).status,403);
 const customerLogin=await call('/api/auth/login',customer,customerCookie);assert.equal(customerLogin.status,200);
 const newCookie=customerLogin.headers.get('set-cookie').split(';')[0];assert.notEqual(newCookie,customerCookie);
 assert.equal((await (await call('/api/auth/session',undefined,customerCookie)).json()).user,null);
 await DB.prepare('UPDATE account_sessions SET expires_at=0').run();
 assert.equal((await (await call('/api/auth/session',undefined,newCookie)).json()).user,null);
 const admin2=await call('/api/auth/login',{username:env.ADMIN_USERNAME,password:'admin-test-password'});
 const cookie2=admin2.headers.get('set-cookie').split(';')[0];env.ADMIN_PASSWORD_HASH=await hash('changed-admin-password',12);
 assert.equal((await call('/api/admin/products',undefined,cookie2)).status,403);
 for(let i=0;i<10;i++)assert.equal((await call('/api/auth/login',{username:'missing_user',password:'incorrect-password'})).status,401);
 assert.equal((await call('/api/auth/login',{username:'missing_user',password:'incorrect-password'})).status,429);
 assert.equal((await call('/api/admin/products',undefined,'__Host-up_session='+('a'.repeat(64)))).status,403);
 DB.close();
});
