import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {hash} from 'bcryptjs';
import {createWorker} from '../worker.mjs';
import {database} from '../scripts/sqlite-adapter.mjs';
async function setup(){const DB=database();for(const f of (await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())await DB.exec(await fs.readFile('drizzle/'+f,'utf8'));const env={DB,ADMIN_USERNAME:'testadmin',ADMIN_PASSWORD_HASH:await hash('admin-test-123',10)},w=createWorker({},await fs.readFile('db/schema.sql','utf8'));const call=(path,method='GET',data,cookie='',origin='https://shop.test')=>w.fetch(new Request('https://shop.test'+path,{method,headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json','cf-connecting-ip':'192.0.2.4'},...(data===undefined?{}:{body:JSON.stringify(data)})}),env);const login=await call('/api/auth/login','POST',{username:'testadmin',password:'admin-test-123'});const admin=login.headers.get('set-cookie').split(';')[0];return {DB,env,call,admin};}
test('product options save atomically, public visibility, private persistent favorites, confirmed store content',async()=>{
 const {DB,call,admin}=await setup();
 const p={name:'Produto de teste',category:'iPhone',description:'Descrição',price:10000,stock:5,low_stock:2,image:'https://example.com/photo.jpg',condition:'Seminovo',featured:false,published:true,details:{gallery:['https://example.com/other.jpg'],battery:89,warranty:'Garantia confirmada para teste',variants:[{color:'Preto',capacity:'128 GB',price:120000,stock:2},{color:'Branco',capacity:'256 GB',price:150000,stock:0}]}};
 const created=await call('/api/admin/products','POST',p,admin);assert.equal(created.status,201);const {product}=await created.json();assert.equal(product.stock,2);assert.equal(product.price,120000);
 const detail='/api/products/'+product.id,edit='/api/admin/products/'+product.id,favorite='/api/favorites/'+product.id;
 assert.equal((await (await call(detail)).json()).product.details.battery,89);
 const bad={...p,details:{...p.details,gallery:['javascript:alert(1)']}};assert.equal((await call(edit,'PUT',{...bad,version:1},admin)).status,400);
 assert.equal((await call(edit,'PUT',{...p,version:1,details:{...p.details,battery:90}},admin)).status,200);
 assert.equal((await call(edit,'PUT',{...p,version:1,details:{battery:40}},admin)).status,409);
 assert.equal((await (await call(detail)).json()).product.details.battery,90);
 const register=async username=>{const r=await call('/api/auth/register','POST',{username,password:'customer-123',name:'Teste'});return r.headers.get('set-cookie').split(';')[0];};
 const a=await register('cliente_a'),b=await register('cliente_b');
 assert.equal((await call(favorite,'PUT',undefined,'')).status,401);assert.equal((await call(favorite,'PUT',undefined,a,'https://evil.test')).status,403);
 assert.equal((await call(favorite,'PUT',undefined,a)).status,200);assert.equal((await call(favorite,'PUT',undefined,a)).status,200);
 assert.equal((await (await call('/api/favorites','GET',undefined,a)).json()).products.length,1);assert.equal((await (await call('/api/favorites','GET',undefined,b)).json()).products.length,0);
 await call(favorite,'DELETE',undefined,b);assert.equal((await (await call('/api/favorites','GET',undefined,a)).json()).products.length,1);
 assert.equal((await call(edit,'PUT',{...p,version:2,published:false},admin)).status,200);assert.equal((await call(detail)).status,404);
 const hidden=(await (await call('/api/favorites','GET',undefined,a)).json()).products[0];assert.equal(hidden.available,false);assert.equal(hidden.image,undefined);assert.equal(hidden.price,undefined);assert.equal((await call(favorite,'PUT',undefined,b)).status,404);
 assert.equal((await call('/api/admin/reviews','PUT',{version:0,content:{reviews:[]}},a)).status,403);
 assert.equal((await call('/api/admin/reviews','PUT',{version:0,content:{reviews:[{name:'Pessoa',text:'Teste',approved:false}]}},admin)).status,400);
 await DB.prepare('INSERT INTO store_content(id,data,version) VALUES(1,?,1)').bind(JSON.stringify({pickup:'Retirada antiga',reviews:[]})).run();
 assert.equal((await call('/api/admin/reviews','PUT',{version:1,content:{reviews:[{name:'Pessoa',text:'Teste autorizado',approved:true}]}},admin)).status,200);
 const reviews=await (await call('/api/reviews')).json();assert.equal(reviews.reviews[0].text,'Teste autorizado');assert.equal(reviews.pickup,undefined);
 assert.equal((await call('/api/store')).status,404);assert.equal((await call('/api/admin/store','GET',undefined,admin)).status,404);
 assert.equal(JSON.parse((await DB.prepare('SELECT data FROM store_content WHERE id=1').first()).data).pickup,'Retirada antiga');
 assert.equal((await call('/api/admin/reviews','PUT',{version:1,content:{reviews:[]}},admin)).status,409);DB.close();
});
test('recovery key requires current password, hashed storage, single use, session revocation and admin parity',async()=>{
 const {DB,env,call,admin}=await setup();
 const original='customer-test-123',next='new-customer-123';
 const reg=await call('/api/auth/register','POST',{username:'recovery_customer',password:original,name:'Teste'}),customer=reg.headers.get('set-cookie').split(';')[0];
 assert.equal((await call('/api/auth/recovery-key','POST',{password:original})).status,401);
 assert.equal((await call('/api/auth/recovery-key','POST',{password:'wrong-password'},customer)).status,401);
 assert.equal((await call('/api/auth/recovery-key','POST',{password:original},customer,'https://evil.test')).status,403);
 const code=(await (await call('/api/auth/recovery-key','POST',{password:original},customer)).json()).code;assert.match(code,/^[a-f0-9-]{55}$/);
 const row=await DB.prepare('SELECT * FROM account_security').first();assert.notEqual(row.recovery_hash,code.replaceAll('-',''));assert.equal(row.password_hash,null);
 const reset={username:'recovery_customer',code,password:next};
 assert.equal((await call('/api/auth/reset-password','POST',{...reset,username:'testadmin'})).status,401);
 assert.equal((await call('/api/auth/reset-password','POST',reset)).status,200);
 assert.equal((await (await call('/api/auth/session','GET',undefined,customer)).json()).user,null);
 assert.equal((await call('/api/auth/reset-password','POST',reset)).status,401);
 assert.equal((await call('/api/auth/login','POST',{username:reset.username,password:original})).status,401);
 assert.equal((await call('/api/auth/login','POST',{username:reset.username,password:next})).status,200);
 const adminCode=(await (await call('/api/auth/recovery-key','POST',{password:'admin-test-123'},admin)).json()).code;
 assert.equal((await call('/api/auth/reset-password','POST',{username:'testadmin',password:'new-admin-123',code:adminCode})).status,200);
 assert.equal((await call('/api/admin/products','GET',undefined,admin)).status,403);
 const fresh=await call('/api/auth/login','POST',{username:'testadmin',password:'new-admin-123'});assert.equal(fresh.status,200);const cookie=fresh.headers.get('set-cookie').split(';')[0];
 assert.equal((await call('/api/admin/products','GET',undefined,cookie)).status,200);
 env.ADMIN_PASSWORD_HASH=await hash('rotated-env-123',10);assert.equal((await call('/api/admin/products','GET',undefined,cookie)).status,403);assert.equal((await call('/api/auth/login','POST',{username:'testadmin',password:'new-admin-123'})).status,401);
 for(let i=0;i<6;i++){const r=await call('/api/auth/reset-password','POST',{username:'unknown',password:'whatever-123',code:'a'.repeat(48)});assert.equal(r.status,i<5?401:429);}DB.close();
});
