import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {hash} from 'bcryptjs';
import {createWorker} from '../worker.mjs';
import {database} from '../scripts/sqlite-adapter.mjs';

test('private profiles and avatars persist and cannot modify another account or role',async()=>{
 const DB=database(),files=new Map();
 const BUCKET={async put(k,v){files.set(k,v);},async get(k){return files.has(k)?{body:files.get(k)}:null;},async delete(k){files.delete(k);}};
 const env={DB,BUCKET,ADMIN_USERNAME:'admin',ADMIN_PASSWORD_HASH:await hash('admin-test-password',12)};
 for(const file of (await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())await DB.exec(await fs.readFile('drizzle/'+file,'utf8'));
 const schema=await fs.readFile('db/schema.sql','utf8'),w=createWorker({},schema);
 const call=(path,method='GET',data,cookie='',origin='https://shop.test',type='application/json')=>w.fetch(new Request('https://shop.test'+path,{method,headers:{Cookie:cookie,Origin:origin,'Content-Type':type},...(data===undefined?{}:{body:type==='application/json'?JSON.stringify(data):data})}),env);
 const register=async username=>{const r=await call('/api/auth/register','POST',{username,name:'Cliente '+username,password:'customer-password'});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];};
 const a=await register('cliente_a'),b=await register('cliente_b');
 assert.equal((await call('/api/auth/profile')).status,401);
 assert.equal((await call('/api/auth/avatar')).status,401);
 let profile=(await (await call('/api/auth/profile','GET',undefined,a)).json()).profile;
 assert.equal(profile.name,'Cliente cliente_a');assert.equal(profile.version,0);
 const data={name:'Nome atualizado',email:'pessoa@example.com',phone:'(35) 99999-9999',city:'Varginha',state:'MG',version:0};
 assert.equal((await call('/api/auth/profile','PUT',data,a,'https://evil.test')).status,403);
 assert.equal((await call('/api/auth/profile','PUT',{...data,role:'admin'},a)).status,400);
 assert.equal((await call('/api/auth/profile','PUT',{...data,id:'cliente_b'},a)).status,400);
 assert.equal((await call('/api/auth/profile','PUT',{...data,email:'invalid'},a)).status,400);
 assert.equal((await call('/api/auth/profile','PUT',{...data,state:'XX'},a)).status,400);
 assert.equal((await call('/api/auth/profile','PUT',{...data,name:''},a)).status,400);
 const saved=await call('/api/auth/profile','PUT',data,a);assert.equal(saved.status,200);profile=(await saved.json()).profile;assert.equal(profile.email,data.email);assert.equal(profile.version,1);
 assert.equal((await call('/api/auth/profile','PUT',data,a)).status,409);
 assert.equal((await (await call('/api/auth/profile','GET',undefined,b)).json()).profile.email,'');
 assert.equal((await (await call('/api/auth/session','GET',undefined,a)).json()).user.name,data.name);
 assert.equal((await call('/api/admin/products','GET',undefined,a)).status,403);
 const restart=createWorker({},schema);const persisted=await restart.fetch(new Request('https://shop.test/api/auth/profile',{headers:{Cookie:a}}),env);assert.equal((await persisted.json()).profile.phone,data.phone);
 assert.equal((await call('/api/auth/avatar','POST','<svg></svg>',a,'https://shop.test','image/svg+xml')).status,415);
 assert.equal((await call('/api/auth/avatar','POST',new Uint8Array(140000),a,'https://shop.test','image/jpeg')).status,413);
 assert.equal((await call('/api/auth/avatar','POST',new Uint8Array([0,1,2]),a,'https://shop.test','image/jpeg')).status,400);
 const jpeg=new Uint8Array([255,216,255,224,0,0,255,217]);
 assert.equal((await call('/api/auth/avatar','POST',jpeg,a,'https://evil.test','image/jpeg')).status,403);
 const photo=await call('/api/auth/avatar','POST',jpeg,a,'https://shop.test','image/jpeg');assert.equal(photo.status,200);assert.equal(files.size,1);const photoProfile=(await photo.json()).profile;assert.match(photoProfile.avatar,/^\/api\/auth\/avatar\?v=/);
 const image=await call(photoProfile.avatar,'GET',undefined,a);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/jpeg');assert.equal(image.headers.get('cache-control'),'private, no-store');
 assert.equal((await call(photoProfile.avatar,'GET',undefined,b)).status,404);
 assert.equal((await call('/api/auth/avatar','POST',jpeg,a,'https://shop.test','image/jpeg')).status,200);assert.equal(files.size,1);
 assert.equal((await call('/api/auth/avatar','DELETE',undefined,a)).status,200);assert.equal(files.size,0);
 assert.equal((await call('/api/auth/avatar','GET',undefined,a)).status,404);
 assert.equal((await call('/api/auth/profile','PUT',{...data,email:'',phone:'',city:'',state:'',version:1},a)).status,200);
 const admin=await call('/api/auth/login','POST',{username:'admin',password:'admin-test-password'});const adminCookie=admin.headers.get('set-cookie').split(';')[0];
 assert.equal((await call('/api/auth/profile','PUT',{...data,name:'Equipe Up Smart'},adminCookie)).status,200);
 assert.equal((await (await call('/api/auth/session','GET',undefined,adminCookie)).json()).user.role,'admin');
 assert.equal((await call('/api/admin/products','GET',undefined,adminCookie)).status,200);
 await call('/api/auth/logout','POST',{},a);
 assert.equal((await call('/api/auth/profile','GET',undefined,a)).status,401);
 DB.close();
});
