CREATE TABLE IF NOT EXISTS products (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, description TEXT NOT NULL DEFAULT '',
 price INTEGER, stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0), low_stock INTEGER NOT NULL DEFAULT 2 CHECK(low_stock>=0),
 image TEXT NOT NULL DEFAULT '', condition TEXT NOT NULL DEFAULT 'Novo', featured INTEGER NOT NULL DEFAULT 0,
 published INTEGER NOT NULL DEFAULT 1, archived INTEGER NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS settings (id INTEGER PRIMARY KEY CHECK(id=1), theme TEXT NOT NULL DEFAULT 'light', accent TEXT NOT NULL DEFAULT 'orange', version INTEGER NOT NULL DEFAULT 1);
INSERT OR IGNORE INTO settings(id,theme,accent) VALUES(1,'light','orange');
